### ISSUE TITLE
container image prepare fails with TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by fultonj** [cjeanner/tripleo-lab#36]
Execution of the generated `deploy-overcloud.sh` script fails with the following error:

 TypeError: 'NoneType' object does not support item assignment

when it runs the following:
```
stdbuf -i0 -o0 -e0 openstack tripleo container image prepare \
  -e ~/local_images.yaml \
  --output-env-file ~/overcloud-yml/containers-env-file.yaml
```

**Comment by cjeanner** [comment]
guess we can close that one since the PR was merged, right?

**Comment by fultonj** [comment]
yes, it was solved by the PR.
