### ISSUE TITLE
podman should default on overcloud if stein is newer

### ISSUE THREAD

**Issue by fultonj** [cjeanner/tripleo-lab#42]
Despite container CLI being set correctly AFAICT [1] my overcloud with cent7 is still using docker [2]. Note that my undercloud is correctly using podman [3]. Do I maybe need to remove docker from my overcloud image to get it working with podman? Might this be a Tripleo bug? Or am I just using it wrong? 

[1]
```
(undercloud) [stack@undercloud overcloud-yml]$ cat container-cli.yaml 
---
parameter_defaults:
  ContainerCli: podman
(undercloud) [stack@undercloud overcloud-yml]$ 
```

[2]
```
[root@overcloud-cephstorage-0 ~]# podman ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
[root@overcloud-cephstorage-0 ~]# docker ps
CONTAINER ID        IMAGE                                                              COMMAND                  CREATED             STATUS                  PORTS               NAMES
a33de601c1e8        docker.io/tripleomaster/centos-binary-cron:current-tripleo         "dumb-init --singl..."   18 hours ago        Up 18 hours (healthy)                       logrotate_crond
bd811df94a98        docker.io/ceph/daemon:v4.0.0-stable-4.0-nautilus-centos-7-x86_64   "/opt/ceph-contain..."   19 hours ago        Up 19 hours                                 ceph-osd-1
[root@overcloud-cephstorage-0 ~]# 
```

[3] 
```
[stack@undercloud ~]$ sudo podman ps | head 
CONTAINER ID  IMAGE                                                                            COMMAND               CREATED       STATUS           PORTS  NAMES
3b7eb9c28a8e  docker.io/tripleomaster/centos-binary-neutron-dhcp-agent:current-tripleo         dumb-init --singl...  20 hours ago  Up 20 hours ago         neutron-dnsmasq-qdhcp-1ec665b2-54c7-4724-b852-0ba2ef28b56b
a6bfe4f146cc  docker.io/tripleomaster/centos-binary-nova-compute-ironic:current-tripleo        dumb-init --singl...  20 hours ago  Up 20 hours ago         nova_compute
92e8df5b3977  docker.io/tripleomaster/centos-binary-ironic-inspector:current-tripleo           dumb-init --singl...  20 hours ago  Up 20 hours ago         ironic_inspector_dnsmasq
9903096027f8  docker.io/tripleomaster/centos-binary-ironic-inspector:current-tripleo           dumb-init --singl...  20 hours ago  Up 20 hours ago         ironic_inspector
5fb11db09d05  docker.io/tripleomaster/centos-binary-ironic-pxe:current-tripleo                 dumb-init --singl...  20 hours ago  Up 20 hours ago         ironic_pxe_http
d6cefcec82f3  docker.io/tripleomaster/centos-binary-ironic-pxe:current-tripleo                 dumb-init --singl...  20 hours ago  Up 20 hours ago         ironic_pxe_tftp
a054118ce406  docker.io/tripleomaster/centos-binary-ironic-conductor:current-tripleo           dumb-init --singl...  20 hours ago  Up 20 hours ago         ironic_conductor
2c371925e8e9  docker.io/tripleomaster/centos-binary-ironic-neutron-agent:current-tripleo       dumb-init --singl...  20 hours ago  Up 20 hours ago         ironic_neutron_agent
7de16abf61fb  docker.io/tripleomaster/centos-binary-mistral-api:current-tripleo                dumb-init --singl...  20 hours ago  Up 20 hours ago         mistral_api
[stack@undercloud ~]$ which docker
/usr/bin/which: no docker in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/stack/.local/bin:/home/stack/bin:/home/stack/.local/bin:/home/stack/bin)
[stack@undercloud ~]$ 
```

**Comment by cjeanner** [comment]
Hey,
I have an env file for setting podman as container engine:
```YAML
undercloud_config:
  - section: DEFAULT
    option: container_cli
    value: podman
standalone_container_cli: podman
overcloud_container_cli: podman
```

You have such an env file in the "environments" directory, you may pass it using `-e @environments/podman.yaml` in the ansible-playbook CLI.

Lemme know if it sorts your issue.

**Comment by fultonj** [comment]
I used 6eb13b6 and deployed my undercloud with the following:
```
 ansible-playbook -i inventory.yaml builder.yaml -e @environments/podman.yaml --skip-tags validations,metrics
```
However I still ended up with a deploy-overcloud.sh containing the following. I can easily workaround it but is that your expected behavior? 
```
(undercloud) [stack@undercloud ~]$ cat deploy-overcloud.sh 
#!/bin/bash

source ~/stackrc
stdbuf -i0 -o0 -e0 openstack tripleo container image prepare \
  -e ~/local_images.yaml \
  --output-env-file ~/overcloud-yml/containers-env-file.yaml

stdbuf -i0 -o0 -e0 openstack overcloud deploy \
  --templates /usr/share/openstack-tripleo-heat-templates/ \
  --environment-directory ~/overcloud-yml \
  -e /usr/share/openstack-tripleo-heat-templates/environments/disable-telemetry.yaml \
  -e /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml \
  -e /usr/share/openstack-tripleo-heat-templates/environments/enable-swap.yaml \
  -e /usr/share/openstack-tripleo-heat-templates/environments/docker-ha.yaml \
    --ntp-server pool.ntp.org --libvirt-type qemu 2>&1 | tee -a ~/deploy-overcloud.log
ret_val=$?

if [ $ret_val -ne 0 ] && [ -n $1 ] && [ "$1" = '--delete-if-fail' ]; then
  openstack overcloud delete overcloud --yes
fi
(undercloud) [stack@undercloud ~]$ 
```

**Comment by cjeanner** [comment]
hmm, you're having multiple controllers right? On CentOS7? if so, it won't work for now, because of pacemaker version - it doesn't know about podman. You want to talk to Michele for more details :)

**Comment by fultonj** [comment]
> hmm, you're having multiple controllers right? On CentOS7? 

Yes. Yes.

> if so, it won't work for now, because of pacemaker version - it doesn't know about podman. You want to talk to Michele for more details :)

OK.

**Comment by bilalbinameer** [comment]
I am having an issue in ha deployment of tripleo stein
I am using environment/docker-ha.yaml and changed ContainerCli from docker to podman in it.
pacemaker errors with haproxy_init_bundle container 
Error: pcs -f /var/lib/pacemaker/cib/puppet-cib-backup20190909-10-1g3ftxy create failed: Error: 'podman' is not a valid container type value, use docker
Error: /Stage[main]/Tripleo::Profile::Pacemaker::Haproxy_bundle/Pacemaker::Resource::Bundle[haproxy-bundle]/Pcmk_bundle[haproxy-bundle]/ensure
: change from 'absent' to 'present' failed: pcs -f /var/lib/pacemaker/cib/puppet-cib-backup20190909-10-1g3ftxy create failed: Error: 'podman' 
is not a valid container type value, use docker
Notice: /Stage[main]/Tripleo::Profile::Pacemaker::Haproxy_bundle/Tripleo::Pacemaker::Haproxy_with_vip[haproxy_and_control_vip]/Pacemaker::Cons
traint::Order[control_vip-then-haproxy]/Pcmk_constraint[order-ip-10.81.40.7-haproxy-bundle]: Dependency Pcmk_bundle[haproxy-bundle] has failures: true

I am a newbie and dont know what to do.

**Comment by al-indigo** [comment]
@cjeanner 
Could you tell who is Michele and why it's not supported for real?

https://wiki.clusterlabs.org/wiki/Bundle_Walk-Through sais that "Pacemaker supports podman (since 2.0.1)" and shows an example on podman. We have manually inserted in all containers and host-images Pacemaker 2.0.3 built for CentOS7 and it still complains in the same way

**Comment by cjeanner** [comment]
@al-indigo the pacemaker version shipped in centos-7 doesn't support podman, and iirc there are some elements on the hosts directly.
You can try to ask on #tripleo IRC channel - "bandini" is probable the best one (he's Michele).
